[package]
name = "debug_macros"
version = "0.1.0"
edition = "2024"
description = "Debug-enhanced macros"
repository = "https://github.com/yunsuklee/debug_macros"
license = "MIT OR Apache-2.0"

[dependencies]
